"""Canonical domain models.

Pure Pydantic v2. No persistence, no HTTP, no vendor SDKs — this package is
importable from anywhere and depends on nothing but :mod:`applyuminati.core`.
"""

from applyuminati.core.models.application import (
    ActorKind,
    Application,
    ApplicationArtifact,
    ApplicationEvent,
    ApplicationState,
    allowed_transitions,
    can_transition,
)
from applyuminati.core.models.common import (
    Compensation,
    CompensationPeriod,
    DateRange,
    EmploymentType,
    Location,
    RemoteMode,
    SeniorityLevel,
    seniority_distance,
)
from applyuminati.core.models.job import (
    AtsVendor,
    Job,
    JobSourceRecord,
    PipelineStage,
    SourceTier,
    VerificationState,
    canonicalize_url,
    normalize_company,
    normalize_title,
    title_comparison_key,
)
from applyuminati.core.models.jsonresume import JsonResume
from applyuminati.core.models.memory import (
    ApprovalSignal,
    EditKind,
    LearningSignal,
    MemoryKind,
    MemoryRecord,
    OutcomeRecord,
)
from applyuminati.core.models.profile import (
    CareerProfile,
    EEOPreferences,
    JobTargets,
    PortfolioArtifact,
    QuantifiedMetric,
    QuestionnaireDefault,
    StarStory,
    WordingPreference,
    WorkAuthorizationStatus,
    WorkEligibility,
    WritingStyle,
)
from applyuminati.core.models.questionnaire import (
    AnswerDraft,
    AnswerStatus,
    ApplicationQuestion,
    QuestionKind,
    SensitivityClass,
    classify_sensitivity,
)
from applyuminati.core.models.research import (
    CompanyResearch,
    ResearchFinding,
    ResearchTopic,
)
from applyuminati.core.models.scoring import (
    DimensionScore,
    FitScore,
    MatchedEvidence,
    MissingRequirement,
    Recommendation,
    ScoreDimension,
)
from applyuminati.core.models.task import (
    RunRecord,
    RunState,
    TaskAttempt,
    TaskRecord,
    TaskState,
)

__all__ = [
    "ActorKind",
    "AnswerDraft",
    "AnswerStatus",
    "Application",
    "ApplicationArtifact",
    "ApplicationEvent",
    "ApplicationQuestion",
    "ApplicationState",
    "ApprovalSignal",
    "AtsVendor",
    "CareerProfile",
    "CompanyResearch",
    "Compensation",
    "CompensationPeriod",
    "DateRange",
    "DimensionScore",
    "EEOPreferences",
    "EditKind",
    "EmploymentType",
    "FitScore",
    "Job",
    "JobSourceRecord",
    "JobTargets",
    "JsonResume",
    "LearningSignal",
    "Location",
    "MatchedEvidence",
    "MemoryKind",
    "MemoryRecord",
    "MissingRequirement",
    "OutcomeRecord",
    "PipelineStage",
    "PortfolioArtifact",
    "QuantifiedMetric",
    "QuestionKind",
    "QuestionnaireDefault",
    "Recommendation",
    "RemoteMode",
    "ResearchFinding",
    "ResearchTopic",
    "RunRecord",
    "RunState",
    "ScoreDimension",
    "SeniorityLevel",
    "SensitivityClass",
    "SourceTier",
    "StarStory",
    "TaskAttempt",
    "TaskRecord",
    "TaskState",
    "VerificationState",
    "WordingPreference",
    "WorkAuthorizationStatus",
    "WorkEligibility",
    "WritingStyle",
    "allowed_transitions",
    "can_transition",
    "canonicalize_url",
    "classify_sensitivity",
    "normalize_company",
    "normalize_title",
    "seniority_distance",
    "title_comparison_key",
]
