"""Typer CLI entry point.

Every command calls the same application services as the FastAPI routers —
no CLI-only business logic exists anywhere. Commands that need async services
run them through :func:`asyncio.run` on a fresh event loop.
"""

from __future__ import annotations

import asyncio
import json
import secrets
from pathlib import Path
from typing import Any

import typer
from rich import box
from rich.console import Console
from rich.table import Table

from applyuminati import __version__
from applyuminati.browser.host_protocol import PROTOCOL_VERSION, WEBSOCKET_PATH
from applyuminati.core.errors import ApplyuminatiError
from applyuminati.core.models.application import allowed_transitions
from applyuminati.core.models.browser_host import HostConnectionState
from applyuminati.core.registry import PluginMaturity
from applyuminati.core.security import WeakPasswordError, hash_password
from applyuminati.core.settings import ExecutionMode, get_settings
from applyuminati.services.application_service import ApplicationService
from applyuminati.services.capabilities import collect_capability_matrix
from applyuminati.services.container import ServiceContainer, get_container

app = typer.Typer(
    name="applyuminati",
    help="Local-first, autonomous, LLM-powered job search and application platform.",
    no_args_is_help=True,
)
console = Console()


def _run_async(coro: Any) -> Any:
    return asyncio.run(coro)


def _container() -> ServiceContainer:
    return get_container()


def _sync_sources(container: ServiceContainer) -> None:
    """Apply config.toml to the database before reading source state.

    A config file is the documented way to configure sources, and the CLI is
    the main way to use the product, so the CLI has to honour it the way the
    API lifespan does. Only sources the file names are affected, which is what
    lets `sources disable` stick for a source nobody put in the file.
    """
    _run_async(container.sync_settings_to_db())


# -- init ----------------------------------------------------------------


#: Written by `init` so a fresh install has a file to edit. A config file is how
#: a pip or Docker install configures sources, and env vars cannot carry board
#: tokens comfortably, so this is the documented path rather than a convenience.
_CONFIG_TEMPLATE = """\
# Applyuminati configuration.
#
# This file is authoritative for any source it names. A source you enable with
# `applyuminati sources enable` but do not list here keeps whatever state you
# gave it.

[discovery.sources.greenhouse]
enabled = false

[discovery.sources.greenhouse.options]
# Board tokens, exactly as they appear in a Greenhouse careers URL.
boards = []

[discovery.sources.lever]
enabled = false

[discovery.sources.lever.options]
companies = []

[discovery.sources.local_feed]
enabled = false

[discovery.sources.local_feed.options]
paths = []

# The UI and API password. A strong one was generated for you by `init` and
# written to .env; set it here instead to keep everything in one file.
[security]
enabled = true
# Generated by `applyuminati init`. Change it with: applyuminati auth set-password
password = "{password}"

# Set to research_only for a tighter leash. See SECURITY.md for what the
# guard rails do regardless of this setting.
[execution]
mode = "autonomous_submit"
"""


def _write_config(path: Path, password: str | None) -> None:
    from applyuminati.core.security import hash_password

    # A hash, not the plaintext: the plaintext is printed once and never stored.
    text = _CONFIG_TEMPLATE.replace("{password}", hash_password(password) if password else "")
    path.write_text(text)
    path.chmod(0o600)


def _set_password_in_config(path: Path, password: str) -> None:
    """Replace the password line in an existing config, leaving the rest alone."""
    from applyuminati.core.security import hash_password

    lines = path.read_text().splitlines()
    replaced = False
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("password =") or stripped.startswith("# Generated by"):
            if stripped.startswith("password ="):
                lines[index] = f'password = "{hash_password(password)}"'
                replaced = True
            continue
        if replaced:
            break
    if not replaced:
        lines.append(f'\n[security]\npassword = "{hash_password(password)}"')
    path.write_text("\n".join(lines) + "\n")
    path.chmod(0o600)


def _run_migrations(settings: Any) -> str:
    """Bring the database up to head. Returns the resulting revision.

    Called in-process rather than shelling out to the alembic CLI so a pip
    install has no alembic entry point to find and no alembic.ini to locate.
    """
    from pathlib import Path as _Path

    from alembic import command
    from alembic.config import Config

    # Built from scratch rather than read from alembic.ini: a wheel install has
    # no alembic.ini to find, and the only options that file carries are the two
    # set here. env.py resolves the URL from settings, so nothing is duplicated.
    migrations = _Path(__file__).resolve().parents[1] / "db" / "migrations"
    config = Config()
    config.set_main_option("script_location", str(migrations))
    config.set_main_option("version_table", "alembic_version")
    config.set_main_option("path_separator", "os")
    config.set_main_option("sqlalchemy.url", settings.resolved_database_url)
    command.upgrade(config, "head")
    # Read the revision back through the app's own helper rather than
    # alembic.current, which reopens the config and trips over the stream the
    # Typer runner has already closed.
    from applyuminati.db.session import Database

    # Awaited here rather than returned: this runs from a sync Typer command and
    # an un-awaited coroutine prints as a repr and warns.
    return _run_async(Database(settings).schema_version()) or ""


@app.command()
def init(
    password: str | None = typer.Option(
        None,
        "--password",
        help="UI/API password. One is generated and hashed into config.toml when omitted.",
    ),
) -> None:
    """Set up a new install: directories, schema, config, and a password."""
    settings = get_settings()
    settings.ensure_directories()

    generated = password is None
    if generated and settings.security.password:
        # Already provisioned by an earlier run; never overwrite it.
        generated = False
        password = None
    elif generated:
        password = secrets.token_urlsafe(18)

    if password is not None:
        _check_password_strength(password)

    console.print(f"[green]Initialising Applyuminati at {settings.data_dir}[/green]")

    # 1. Schema. Done here because a manual `alembic upgrade` step is the single
    #    most common reason a first run dies on "no such table".
    try:
        revision = _run_migrations(settings)
    except Exception as exc:
        typer.secho(f"Could not migrate the database: {exc}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    console.print(f"  Schema:   {revision or 'at head'}")

    # 2. Config file, carrying the password. It has to live here rather than in a
    #    .env because pydantic reads .env from the working directory, not from
    #    the data directory, so a generated password in .env was never loaded.
    #    Never clobbered: a user who edited the file has opinions.
    if settings.config_path.is_file():
        console.print(f"  Config:   {settings.config_path} (kept)")
        if password is not None:
            _set_password_in_config(settings.config_path, password)
    else:
        _write_config(settings.config_path, password)
        console.print(f"  Config:   {settings.config_path} (created)")

    # 3. Report. Without a password every API route answers 503
    #    auth.not_configured, so a fresh install that skips this cannot be used.
    if generated and password is not None:
        console.print(f"  Password: generated and written to {settings.config_path}")
        console.print(f"            {password}")
        console.print("            Change it with: applyuminati auth set-password")
    elif password is not None:
        console.print(f"  Password: written to {settings.config_path}")
    else:
        console.print("  Password: already set, left alone")

    console.print(f"  Database: {settings.db_path}")
    console.print(f"  Mode:     {settings.execution_mode.value}")
    console.print("\nNext steps:")
    console.print("  1. Import your resume:  applyuminati profile import resume.json")
    console.print("  2. Enable a source:     edit config.toml, then applyuminati jobs discover")
    console.print("  3. Open the UI:         applyuminati tui")


def _check_password_strength(password: str) -> None:
    from applyuminati.core.security import WeakPasswordError, hash_password

    try:
        hash_password(password)
    except WeakPasswordError as exc:
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc


# -- doctor ---------------------------------------------------------------


@app.command()
def doctor() -> None:
    """Check the health of every component."""
    container = _container()
    _sync_sources(container)

    async def _check() -> None:
        db_ok = await container.database.check()
        schema = await container.database.schema_version()
        async with container.repositories() as repos:
            from applyuminati.services.health_service import HealthService

            svc = HealthService(repos, container.settings, container._llm)
            summary = await svc.summary(db_ok, schema)
            backends = await svc.backends()

        table = Table(title="Applyuminati Doctor")
        table.add_column("Component")
        table.add_column("Status")
        table.add_column("Detail")
        table.add_row("Database", "ok" if db_ok else "FAIL", str(container.settings.db_path))
        table.add_row("Schema", schema or "not migrated", "")
        table.add_row(
            "Profile", "configured" if summary["profile_configured"] else "not imported", ""
        )
        table.add_row("Mode", summary["execution_mode"], "")
        table.add_row(
            "Sources", ", ".join(summary.get("enabled_sources", [])) or "(none enabled)", ""
        )
        console.print(table)

        bt = Table(title="Backends")
        bt.add_column("Kind")
        bt.add_column("Name")
        bt.add_column("State")
        bt.add_column("Detail")
        for kind, reports in [
            ("source", backends.sources),
            ("llm", backends.llm),
            ("browser", backends.browsers),
            ("agent", backends.agents),
            ("email", backends.email),
        ]:
            for report in reports:
                bt.add_row(kind, report.plugin, report.state.value, report.detail[:60])
        console.print(bt)
        if backends.load_errors:
            console.print("[red]Load errors:[/red]")
            for err in backends.load_errors:
                console.print(f"  {err}")

    _run_async(_check())


# -- serve ----------------------------------------------------------------


@app.command()
def serve(
    host: str = typer.Option("127.0.0.1", help="Bind address"),
    port: int = typer.Option(8000, help="Port"),
    reload: bool = typer.Option(False, help="Auto-reload on file changes"),
) -> None:
    """Start the local API server."""
    import uvicorn

    console.print(f"[green]Starting Applyuminati on http://{host}:{port}[/green]")
    uvicorn.run(
        "applyuminati.api.app:app",
        host=host,
        port=port,
        reload=reload,
    )


# -- auth -----------------------------------------------------------------


auth_app = typer.Typer(help="Manage access to the local API and UI.")
app.add_typer(auth_app, name="auth")


@auth_app.command("hash-password")
def auth_hash_password(
    password: str = typer.Option(
        ...,
        prompt=True,
        confirmation_prompt=True,
        hide_input=True,
        help="Read from a prompt so it never lands in shell history.",
    ),
) -> None:
    """Print a PBKDF2 hash to use as the configured password.

    Use this instead of a plaintext password wherever other people can read the
    process environment or the compose file: a shared host, a NAS, a machine with
    other users. The hash verifies logins and cannot be replayed as the password.
    """
    try:
        encoded = hash_password(password)
    except WeakPasswordError as exc:
        console.print(f"[red]{exc}[/red]")
        raise typer.Exit(code=1) from exc
    console.print("\n[green]Add this to config.toml:[/green]")
    console.print(f'\n[security]\npassword = "{encoded}"\n')
    console.print("[green]Or export it:[/green]")
    console.print(f"\nAPPLYUMINATI_SECURITY__PASSWORD='{encoded}'\n")


@auth_app.command("set-password")
def auth_set_password(
    password: str = typer.Option(..., prompt=True, hide_input=True, help="New password"),
) -> None:
    """Set or change the UI/API password. The only way to change it after init."""
    from applyuminati.core.security import WeakPasswordError, hash_password

    try:
        encoded = hash_password(password)
    except WeakPasswordError as exc:
        typer.secho(str(exc), fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    env_path = get_settings().data_dir / ".env"
    lines = (
        [
            ln
            for ln in env_path.read_text().splitlines()
            if not ln.startswith("APPLYUMINATI_SECURITY__PASSWORD")
        ]
        if env_path.is_file()
        else []
    )
    lines.append(f"APPLYUMINATI_SECURITY__PASSWORD={encoded}")
    env_path.write_text("\n".join(lines) + "\n")
    env_path.chmod(0o600)
    console.print(f"[green]Password updated in {env_path}[/green]")


@auth_app.command("status")
def auth_status() -> None:
    """Report whether the API is protected, and how far it is reachable."""
    settings = get_settings()
    security = settings.security
    table = Table(title="Access control")
    table.add_column("Property")
    table.add_column("Value")
    table.add_row("Authentication", "enabled" if security.enabled else "DISABLED")
    table.add_row("Password", "set" if security.configured_secret() else "NOT SET")
    table.add_row("Bind address", settings.server.host)
    table.add_row(
        "Reachable from other machines",
        "yes" if settings.listens_beyond_loopback else "no (loopback only)",
    )
    table.add_row("Secure cookies (HTTPS)", "yes" if security.https_only else "no")
    table.add_row("Session lifetime", f"{security.session_ttl_hours}h")
    console.print(table)
    if security.enabled and not security.configured_secret():
        console.print(
            "[yellow]The API will refuse every request except health and login "
            "until a password is set. Run: applyuminati auth hash-password[/yellow]"
        )


# -- browser hosts --------------------------------------------------------


host_app = typer.Typer(help="Pair and manage Browser Hosts.")
app.add_typer(host_app, name="browser-host")


@host_app.command("pair")
def browser_host_pair(
    host_id: str = typer.Argument(..., help="Stable id the host will identify itself by."),
    display_name: str | None = typer.Option(None, help="Label shown in the UI."),
    server_url: str = typer.Option(
        "http://127.0.0.1:8000", help="Where the host should connect back to."
    ),
) -> None:
    """Mint a pairing credential for a Browser Host.

    The credential is printed once and only the hash is stored, so a copy of the
    database does not let anyone drive the user's browser. Losing it means
    running this command again, which rotates the credential and invalidates the
    old one.
    """
    container = _container()

    async def _pair() -> tuple[str, str]:
        async with container.repositories() as repos:
            paired = await repos.browser_hosts.pair(host_id=host_id, display_name=display_name)
            return paired.record.host_id, paired.secret

    paired_id, secret = _run_async(_pair())
    websocket = server_url.rstrip("/").replace("https://", "wss://").replace("http://", "ws://")
    console.print(f"\n[green]Paired {paired_id}.[/green]")
    console.print("[yellow]This credential is shown once and cannot be recovered.[/yellow]\n")
    console.print("Run on the machine with the browser:\n")
    console.print(
        f"  APPLYUMINATI_HOST_CREDENTIAL='{secret}' \\\n"
        f"    applyuminati-browser-host run --server {websocket}{WEBSOCKET_PATH} \\\n"
        f"    --host-id {paired_id}\n"
    )
    console.print(f"[dim]Protocol version {PROTOCOL_VERSION}[/dim]")


@host_app.command("list")
def browser_host_list() -> None:
    """List paired Browser Hosts and what each can do."""
    container = _container()

    async def _list() -> list[Any]:
        async with container.read_repositories() as repos:
            return await repos.browser_hosts.list()

    records = _run_async(_list())
    if not records:
        console.print("No Browser Hosts paired. Run: applyuminati browser-host pair <id>")
        return
    table = Table(title="Browser Hosts")
    table.add_column("Host")
    table.add_column("Platform")
    table.add_column("State")
    table.add_column("Backends")
    table.add_column("Last seen")
    for record in records:
        # The stored state is a cache of what a previous process knew. This
        # command runs outside the server, so it cannot see live connections and
        # must not claim one.
        state = (
            "disconnected" if record.state is HostConnectionState.CONNECTED else record.state.value
        )
        backends = ", ".join(b.slug for b in record.available_backends()) or "—"
        table.add_row(
            record.display_name or record.host_id,
            record.platform or "—",
            state,
            backends,
            record.last_seen_at.strftime("%Y-%m-%d %H:%M") if record.last_seen_at else "never",
        )
    console.print(table)


@host_app.command("revoke")
def browser_host_revoke(
    host_id: str = typer.Argument(..., help="Host whose credential should stop working."),
) -> None:
    """Withdraw a Browser Host's credential.

    The record is kept so the revocation is auditable and a host that reappears
    is identified as revoked rather than as unknown.
    """
    container = _container()

    async def _revoke() -> bool:
        async with container.repositories() as repos:
            return await repos.browser_hosts.revoke(host_id) is not None

    if _run_async(_revoke()):
        console.print(f"[green]Revoked {host_id}. It can no longer connect.[/green]")
    else:
        console.print(f"[red]No Browser Host called {host_id!r}.[/red]")
        raise typer.Exit(code=1)


# -- profile --------------------------------------------------------------


profile_app = typer.Typer(help="Manage the canonical career profile.")
app.add_typer(profile_app, name="profile")


@profile_app.command("import")
def profile_import(
    path: Path = typer.Argument(..., help="Path to a JSON Resume file"),
    replace: bool = typer.Option(False, "--replace", help="Overwrite an existing profile"),
) -> None:
    """Import a JSON Resume file."""
    container = _container()

    async def _import() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.profile_service import ProfileService

            svc = ProfileService(repos)
            result = await svc.import_from_path(path, replace=replace)
        console.print(f"[green]Imported profile: {result.profile.name}[/green]")
        console.print(f"  Claims:   {result.claims_created}")
        console.print(f"  Metrics:  {result.metrics_extracted}")
        if result.warnings:
            console.print("[yellow]Warnings:[/yellow]")
            for warning in result.warnings:
                console.print(f"  {warning}")

    _run_async(_import())


@profile_app.command("export")
def profile_export(
    path: Path = typer.Argument(..., help="Output path for the JSON Resume file"),
) -> None:
    """Export the current profile as a JSON Resume file."""
    container = _container()

    async def _export() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.profile_service import ProfileService

            svc = ProfileService(repos)
            resume = await svc.export_resume()
        path.write_text(json.dumps(resume, indent=2, ensure_ascii=False), encoding="utf-8")
        console.print(f"[green]Exported to {path}[/green]")

    _run_async(_export())


# -- sources --------------------------------------------------------------


sources_app = typer.Typer(help="Manage job sources.")
app.add_typer(sources_app, name="sources")


@sources_app.command("list")
def sources_list() -> None:
    """List all registered job sources."""
    container = _container()
    _sync_sources(container)

    async def _list() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.source_service import SourceService

            svc = SourceService(repos, container.settings)
            views = await svc.list()
        table = Table(title="Job Sources")
        table.add_column("Slug")
        table.add_column("Name")
        table.add_column("Tier")
        table.add_column("Enabled")
        table.add_column("Health")
        for view in views:
            table.add_row(
                view.slug,
                view.name,
                view.tier,
                "✓" if view.enabled else "",
                view.health.state.value if view.health else "unknown",
            )
        console.print(table)

    _run_async(_list())


@sources_app.command("enable")
def sources_enable(
    slug: str = typer.Argument(..., help="Source slug, e.g. greenhouse"),
) -> None:
    """Enable a job source."""
    container = _container()

    async def _enable() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.source_service import SourceService

            svc = SourceService(repos, container.settings)
            view = await svc.set_enabled(slug, True)
        console.print(f"[green]Enabled source: {view.name}[/green]")

    _run_async(_enable())


@sources_app.command("disable")
def sources_disable(
    slug: str = typer.Argument(..., help="Source slug"),
) -> None:
    """Disable a job source."""
    container = _container()

    async def _disable() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.source_service import SourceService

            svc = SourceService(repos, container.settings)
            view = await svc.set_enabled(slug, False)
        console.print(f"[green]Disabled source: {view.name}[/green]")

    _run_async(_disable())


# -- jobs -----------------------------------------------------------------


jobs_app = typer.Typer(help="Discover, list, and score jobs.")
app.add_typer(jobs_app, name="jobs")


@jobs_app.command("discover")
def jobs_discover(
    source: list[str] = typer.Option(default_factory=list, help="Restrict to these sources"),
    query: list[str] = typer.Option(default_factory=list, help="Search queries"),
) -> None:
    """Run job discovery across enabled sources."""
    container = _container()
    _sync_sources(container)

    async def _discover() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.discovery_service import DiscoveryService

            svc = DiscoveryService(repos, container.settings)
            run = await svc.discover(
                sources=source or None, queries=query or None, triggered_by="cli"
            )
        console.print(f"[green]Discovery complete: {run.state.value}[/green]")
        console.print(f"  Discovered: {run.stats.get('jobs_discovered', 0)}")
        console.print(f"  Created:    {run.stats.get('jobs_created', 0)}")
        console.print(f"  Merged:     {run.stats.get('jobs_merged', 0)}")
        if run.failures:
            console.print("[red]Failures:[/red]")
            for failure in run.failures:
                console.print(f"  {failure}")

    _run_async(_discover())


@jobs_app.command("list")
def jobs_list(
    limit: int = typer.Option(20, help="Maximum results"),
    source: str = typer.Option(None, help="Filter by source"),
) -> None:
    """List discovered jobs."""
    container = _container()

    async def _list() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.job_service import JobService

            svc = JobService(repos)
            page = await svc.list(sources=[source] if source else None, limit=limit)
        table = Table(title=f"Jobs ({page.total} total)")
        table.add_column("Title")
        table.add_column("Company")
        table.add_column("Source(s)")
        table.add_column("Score")
        table.add_column("Rec.")
        table.add_column("State")
        for view in page.items:
            table.add_row(
                view.job.title[:40],
                view.job.company[:20],
                ", ".join(view.job.source_slugs),
                f"{view.score.overall:.2f}" if view.score else "—",
                view.score.recommendation.value if view.score else "—",
                view.application_state.value if view.application_state else "—",
            )
        console.print(table)

    _run_async(_list())


@jobs_app.command("score")
def jobs_score(
    use_llm: bool = typer.Option(False, "--llm", help="Use LLM enrichment"),
    limit: int = typer.Option(100, help="Maximum jobs to score"),
) -> None:
    """Score unscored jobs against the profile."""
    container = _container()

    async def _score() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.scoring_service import ScoringService

            svc = ScoringService(repos, container.settings, container.llm)
            run = await svc.score_jobs(use_llm=use_llm, limit=limit, triggered_by="cli")
        console.print(f"[green]Scoring complete: {run.state.value}[/green]")
        console.print(f"  Scored:  {run.stats.get('scored', 0)}")
        console.print(f"  Failed: {run.stats.get('failed', 0)}")
        if run.failures:
            console.print("[red]Failures:[/red]")
            for failure in run.failures:
                console.print(f"  {failure}")

    _run_async(_score())


# -- capabilities ---------------------------------------------------------


applications_app = typer.Typer(help="Start and inspect applications.")
app.add_typer(applications_app, name="applications")


@applications_app.command("apply")
def applications_apply(
    job_id: str = typer.Argument(..., help="Job id to apply to"),
    mode: str = typer.Option(
        None, help="research_only or autonomous_submit. Defaults to the configured mode."
    ),
) -> None:
    """Start an application for a job. This is the only way to begin applying."""
    from applyuminati.services.attempt_service import AttemptService

    settings = get_settings()
    chosen = ExecutionMode(mode) if mode else settings.execution_mode

    async def _run() -> Any:
        container = _container()
        async with container.repositories() as repos:
            return await AttemptService(repos).start_for_job(
                job_id=job_id, profile=None, mode=chosen
            )

    try:
        attempt = _run_async(_run())
    except ApplyuminatiError as exc:
        typer.secho(f"{exc.message}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    typer.echo(f"Started attempt {attempt.id} (driver={attempt.driver}, mode={chosen.value})")
    typer.echo("Watch it in the TUI Needs You screen, or `applyuminati serve` and open the web UI.")


@applications_app.command("list")
def applications_list(
    limit: int = typer.Option(20, help="Maximum results"),
) -> None:
    """List applications and the state each one is in."""

    async def _run() -> Any:
        container = _container()
        async with container.repositories() as repos:
            return await ApplicationService(repos).list(limit=limit)

    views = _run_async(_run())
    if not views.items:
        typer.echo("No applications yet. Run `applyuminati jobs discover` then `jobs score`.")
        return
    table = Table(title="Applications", box=box.SIMPLE)
    table.add_column("Id", no_wrap=True)
    table.add_column("Company", no_wrap=True)
    table.add_column("Title", overflow="fold")
    table.add_column("State", no_wrap=True)
    for view in views.items:
        table.add_row(
            view.application.id,
            view.job.company,
            view.job.title,
            view.application.state.value,
        )
    console.print(table)


@applications_app.command("show")
def applications_show(
    application_id: str = typer.Argument(..., help="Application id"),
) -> None:
    """Show one application and every legal transition from its current state."""

    async def _run() -> Any:
        container = _container()
        async with container.repositories() as repos:
            return await ApplicationService(repos).get(application_id)

    try:
        view = _run_async(_run())
    except ApplyuminatiError as exc:
        typer.secho(f"{exc.message}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=1) from exc
    typer.echo(f"{view.job.company} — {view.job.title}")
    typer.echo(f"  state:   {view.application.state.value}")
    typer.echo(f"  job id:  {view.job.id}")
    typer.echo(f"  apply:   {view.job.apply_url or '—'}")
    allowed = [state.value for state in allowed_transitions(view.application.state)]
    if allowed:
        typer.echo(f"  actions: {', '.join(allowed)}")


@app.command()
def capabilities() -> None:
    """Print the plugin capability and maturity matrix.

    Generated from the live registries so a README table cannot drift. Nothing
    in this tree claims production_tested: that requires a human run against a
    live employer flow.
    """
    rows = collect_capability_matrix()
    table = Table(title="Capability matrix")
    table.add_column("Kind")
    table.add_column("Slug")
    table.add_column("Maturity")
    table.add_column("Capabilities")
    for row in rows:
        table.add_row(
            row.kind,
            row.slug,
            row.maturity.value,
            ", ".join(row.capabilities) or "—",
        )
    console.print(table)
    claimed = [row for row in rows if row.maturity is PluginMaturity.PRODUCTION_TESTED]
    if claimed:
        console.print("[red]production_tested is reserved for a live employer run.[/red]")
        raise typer.Exit(code=1)


# -- status ---------------------------------------------------------------


@app.command()
def status() -> None:
    """Show the current application pipeline status."""
    container = _container()

    async def _status() -> None:
        async with container.repositories() as repos:
            from applyuminati.services.dashboard_service import DashboardService

            svc = DashboardService(repos)
            view = await svc.build()
        console.print(f"[bold]Applyuminati Status[/bold] (v{__version__})")
        console.print(f"  Total jobs:       {view.total_jobs}")
        console.print(f"  Shortlisted:      {view.shortlisted}")
        console.print(f"  Ready:            {view.ready}")
        console.print(f"  Submitted:        {view.submitted}")
        console.print(f"  Needs attention:  {view.needs_attention}")
        console.print(f"  Scored:           {view.scored} / {view.total_jobs}")
        if view.by_recommendation:
            console.print("\n  By recommendation:")
            for rec, count in sorted(view.by_recommendation.items()):
                console.print(f"    {rec}: {count}")
        if view.latest_run:
            run = view.latest_run
            console.print(f"\n  Latest run: {run.kind} ({run.state.value})")
            console.print(f"    Stats: {run.stats}")

    _run_async(_status())
