"""initial schema

Revision ID: 13629bd800f5
Revises: 
Create Date: 2026-08-28 18:18:18.958332
"""

from __future__ import annotations

from collections.abc import Sequence

import applyuminati.db.base  # noqa: F401 - referenced by UTCDateTime columns
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '13629bd800f5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('company_key', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_research')),
    sa.UniqueConstraint('company_key', name='uq_company_research_key')
    )
    with op.batch_alter_table('company_research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_research_company_key'), ['company_key'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('identity_key', sa.String(length=26), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('company_key', sa.String(length=300), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('title_raw', sa.String(length=400), nullable=False),
    sa.Column('title_key', sa.String(length=400), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('seniority', sa.String(length=32), nullable=False),
    sa.Column('remote_mode', sa.String(length=16), nullable=False),
    sa.Column('employment_type', sa.String(length=24), nullable=False),
    sa.Column('comp_min_annual', sa.Float(), nullable=True),
    sa.Column('comp_max_annual', sa.Float(), nullable=True),
    sa.Column('comp_currency', sa.String(length=8), nullable=True),
    sa.Column('locations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('compensation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_qualifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('posted_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('discovered_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('valid_through', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verification', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('ats', sa.String(length=24), nullable=False),
    sa.Column('merged_job_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('identity_key', name='uq_jobs_identity_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_ats'), ['ats'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_company_key'), ['company_key'], unique=False)
        batch_op.create_index('ix_jobs_company_title', ['company_key', 'title_key'], unique=False)
        batch_op.create_index('ix_jobs_discovered_at', ['discovered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_identity_key'), ['identity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_remote_mode'), ['remote_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_seniority'), ['seniority'], unique=False)
        batch_op.create_index('ix_jobs_stage_verification', ['stage', 'verification'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_title_key'), ['title_key'], unique=False)

    op.create_table('learning_signals',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('artifact_kind', sa.String(length=40), nullable=False),
    sa.Column('artifact_id', sa.String(length=26), nullable=True),
    sa.Column('target_path', sa.String(length=255), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('user_text', sa.Text(), nullable=False),
    sa.Column('edit_kinds', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=True),
    sa.Column('application_id', sa.String(length=26), nullable=True),
    sa.Column('prompt_version', sa.String(length=48), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('derived_memory_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_signals'))
    )
    with op.batch_alter_table('learning_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_signals_artifact_kind'), ['artifact_kind'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=True),
    sa.Column('prompt_version', sa.String(length=48), nullable=True),
    sa.Column('run_id', sa.String(length=26), nullable=True),
    sa.Column('task_id', sa.String(length=26), nullable=True),
    sa.Column('started_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('failure_category', sa.String(length=40), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('validation_retries', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_provider'), ['provider'], unique=False)
        batch_op.create_index('ix_llm_calls_run_started', ['run_id', 'started_at'], unique=False)

    op.create_table('memory_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('supporting_observations', sa.Integer(), nullable=False),
    sa.Column('contradicting_observations', sa.Integer(), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('superseded_by', sa.String(length=26), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_records'))
    )
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.create_index('ix_memory_active', ['kind', 'superseded_by'], unique=False)
        batch_op.create_index('ix_memory_kind_scope_key', ['kind', 'scope', 'key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_records_kind'), ['kind'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('application_id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('days_to_outcome', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('ats', sa.String(length=24), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('resume_variant_id', sa.String(length=26), nullable=True),
    sa.Column('causation_known', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outcomes'))
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outcomes_application_id'), ['application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outcomes_outcome'), ['outcome'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('resume', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('profile_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('label', name=op.f('uq_profiles_label'))
    )
    op.create_table('runs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('started_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('failures', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('triggered_by', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_runs_kind_started', ['kind', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_state'), ['state'], unique=False)

    op.create_table('source_states',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('health_state', sa.String(length=20), nullable=False),
    sa.Column('health_detail', sa.Text(), nullable=False),
    sa.Column('last_checked_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_run_jobs', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_source_states'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('run_id', sa.String(length=26), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('resume_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('scheduled_for', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failure_category', sa.String(length=40), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('attempted_strategies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_idempotency', ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_state'), ['state'], unique=False)
        batch_op.create_index('ix_tasks_state_scheduled', ['state', 'scheduled_for', 'priority'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=False),
    sa.Column('profile_id', sa.String(length=26), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('fit_score_id', sa.String(length=26), nullable=True),
    sa.Column('submission_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_applications_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('job_id', 'profile_id', name='uq_applications_job_profile')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_state_updated', ['state', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_submission_fingerprint'), ['submission_fingerprint'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('profile_id', sa.String(length=26), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('superseded_by', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_claims_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_level'), ['level'], unique=False)
        batch_op.create_index('ix_claims_profile_active', ['profile_id', 'superseded_by'], unique=False)
        batch_op.create_index('ix_claims_profile_level', ['profile_id', 'level'], unique=False)

    op.create_table('fit_scores',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=False),
    sa.Column('profile_id', sa.String(length=26), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('baseline_overall', sa.Float(), nullable=True),
    sa.Column('scorer_version', sa.String(length=48), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('llm_prompt_version', sa.String(length=48), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('dimensions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('matched_evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('missing_requirements', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uncertainties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('scored_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_fit_scores_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_fit_scores_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fit_scores'))
    )
    with op.batch_alter_table('fit_scores', schema=None) as batch_op:
        batch_op.create_index('ix_fit_scores_job_profile', ['job_id', 'profile_id', 'scored_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_scores_overall'), ['overall'], unique=False)
        batch_op.create_index(batch_op.f('ix_fit_scores_recommendation'), ['recommendation'], unique=False)

    op.create_table('job_sources',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('first_seen_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_sources_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources')),
    sa.UniqueConstraint('source', 'source_job_id', name='uq_job_sources_source_job')
    )
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.create_index('ix_job_sources_canonical_url', ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_sources_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_sources_source'), ['source'], unique=False)

    op.create_table('application_artifacts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('application_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('bytes_written', sa.Integer(), nullable=True),
    sa.Column('created_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('evidence_claim_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_artifacts_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_artifacts'))
    )
    with op.batch_alter_table('application_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_artifacts_application_id'), ['application_id'], unique=False)

    op.create_table('application_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('application_id', sa.String(length=26), nullable=False),
    sa.Column('occurred_at', applyuminati.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=True),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('actor_detail', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('failure_category', sa.String(length=40), nullable=True),
    sa.Column('run_id', sa.String(length=26), nullable=True),
    sa.Column('task_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_events_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_events'))
    )
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.create_index('ix_application_events_app_time', ['application_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_events', schema=None) as batch_op:
        batch_op.drop_index('ix_application_events_app_time')

    op.drop_table('application_events')
    with op.batch_alter_table('application_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_artifacts_application_id'))

    op.drop_table('application_artifacts')
    with op.batch_alter_table('job_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_sources_source'))
        batch_op.drop_index(batch_op.f('ix_job_sources_job_id'))
        batch_op.drop_index('ix_job_sources_canonical_url')

    op.drop_table('job_sources')
    with op.batch_alter_table('fit_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fit_scores_recommendation'))
        batch_op.drop_index(batch_op.f('ix_fit_scores_overall'))
        batch_op.drop_index('ix_fit_scores_job_profile')

    op.drop_table('fit_scores')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_profile_level')
        batch_op.drop_index('ix_claims_profile_active')
        batch_op.drop_index(batch_op.f('ix_claims_level'))

    op.drop_table('claims')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_submission_fingerprint'))
        batch_op.drop_index('ix_applications_state_updated')

    op.drop_table('applications')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_state_scheduled')
        batch_op.drop_index(batch_op.f('ix_tasks_state'))
        batch_op.drop_index(batch_op.f('ix_tasks_run_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_kind'))
        batch_op.drop_index('ix_tasks_idempotency')

    op.drop_table('tasks')
    op.drop_table('source_states')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_state'))
        batch_op.drop_index('ix_runs_kind_started')
        batch_op.drop_index(batch_op.f('ix_runs_kind'))

    op.drop_table('runs')
    op.drop_table('profiles')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outcomes_outcome'))
        batch_op.drop_index(batch_op.f('ix_outcomes_job_id'))
        batch_op.drop_index(batch_op.f('ix_outcomes_application_id'))

    op.drop_table('outcomes')
    with op.batch_alter_table('memory_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_records_kind'))
        batch_op.drop_index('ix_memory_kind_scope_key')
        batch_op.drop_index('ix_memory_active')

    op.drop_table('memory_records')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_calls_run_started')
        batch_op.drop_index(batch_op.f('ix_llm_calls_provider'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('learning_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_signals_artifact_kind'))

    op.drop_table('learning_signals')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title_key'))
        batch_op.drop_index('ix_jobs_stage_verification')
        batch_op.drop_index(batch_op.f('ix_jobs_seniority'))
        batch_op.drop_index(batch_op.f('ix_jobs_remote_mode'))
        batch_op.drop_index(batch_op.f('ix_jobs_identity_key'))
        batch_op.drop_index('ix_jobs_discovered_at')
        batch_op.drop_index('ix_jobs_company_title')
        batch_op.drop_index(batch_op.f('ix_jobs_company_key'))
        batch_op.drop_index(batch_op.f('ix_jobs_canonical_url'))
        batch_op.drop_index(batch_op.f('ix_jobs_ats'))

    op.drop_table('jobs')
    with op.batch_alter_table('company_research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_research_company_key'))

    op.drop_table('company_research')
    # ### end Alembic commands ###
